filter:
    excluded_paths: [vendor/*, tests/*, .tx/*, languages/*, includes/libs/facebook/*, includes/libs/bitly/*, includes/libs/linkedin/*, includes/libs/twitter/*, includes/libs/OAuth.php, bin/*, fonts/*, images/*, scripts/* ]
before_commands:
    - 'composer install --dev --prefer-source'
tools:
    external_code_coverage:
            timeout: 900    # wait for 15 minutes instead of 5
    php_mess_detector:
        config:
            code_size_rules:
                cyclomatic_complexity:  false
                npath_complexity:     false
                excessive_method_length:  false
                excessive_class_length:  false
                excessive_parameter_list:  false
                excessive_public_count:  false
                too_many_fields:      false
                too_many_methods:     false
                excessive_class_complexity:  false

    php_code_sniffer:
      config:
        standard: "WordPress"
    sensiolabs_security_checker: true
    php_code_coverage: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests, .tx, languages, includes/libs/bitly, includes/libs/facebook, includes/libs/linkedin, includes/libs/twitter, bin, assets, templates]
    php_cpd:
        enabled: true
        excluded_dirs: [vendor, tests, .tx, languages, includes/libs/bitly, includes/libs/facebook, includes/libs/linkedin, includes/libs/twitter, bin, assets, templates]
checks:
    php:
        fix_php_opening_tag: false
        remove_php_closing_tag: false
        one_class_per_file: false
        side_effects_or_types: false
        no_mixed_inline_html: false
        require_braces_around_control_structures: false
        php5_style_constructor: false
        no_global_keyword: false
        avoid_usage_of_logical_operators: false
        psr2_class_declaration: false
        no_underscore_prefix_in_properties: false
        no_underscore_prefix_in_methods: false
        blank_line_after_namespace_declaration: false
        single_namespace_per_use: false
        psr2_switch_declaration: false
        psr2_control_structure_declaration: false
        avoid_superglobals: false
        security_vulnerabilities: false
        no_exit: false
coding_style:
    php:
        indentation:
            general:
                use_tabs: true
        spaces:
            before_parentheses:
                closure_definition: true
            around_operators:
                negation: true
            within:
                array_initializer: true
                function_call: true
                function_declaration: true
